Format indentation with 4 spaces

diff --git a/.github/workflows/10-execution-flow.yaml b/.github/workflows/10-execution-flow.yaml
--- a/.github/workflows/10-execution-flow.yaml
+++ b/.github/workflows/10-execution-flow.yaml
@@ -1,54 +1,54 @@
 name: 10 - Controlling the Execution Flow
 
 on:
-  workflow_dispatch:
-    inputs:
-      pass-unit-tests:
-        type: boolean
-        description: Whether unit tests will pass or not
-        default: true
+    workflow_dispatch:
+        inputs:
+            pass-unit-tests:
+                type: boolean
+                description: Whether unit tests will pass or not
+                default: true
 
 jobs:
-  lint-build:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Lint and build
-        run: echo "Linting and building project"
-  unit-tests:
-    runs-on: ubuntu-latest
-    # Prevents a workflow run from failing when a job fails. Set to true to allow a workflow run to pass when this job fails.
-    # continue-on-error: true
-    steps:
-      - name: Running unit tests
-        run: echo "Running tests..."
-      - name: Failing tests
-        if: ${{ !inputs.pass-unit-tests }}
-        run: exit 1
-  deploy-nonprod:
-    runs-on: ubuntu-latest
-    needs:
-      - lint-build
-      - unit-tests
-    steps:
-      - name: Deploying to nonprod
-        run: echo "Deploying to nonprod..."
-  e2e-tests:
-    runs-on: ubuntu-latest
-    needs: deploy-nonprod
-    steps:
-      - name: Running E2E tests
-        run: echo "Running E2E tests"
-  load-tests:
-    runs-on: ubuntu-latest
-    needs: deploy-nonprod
-    steps:
-      - name: Running load tests
-        run: echo "Running load tests"
-  deploy_prod:
-    runs-on: ubuntu-latest
-    needs:
-      - e2e-tests
-      - load-tests
-    steps:
-      - name: Deploying to prod
-        run: echo "Deploying to prod..."
+    lint-build:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Lint and build
+              run: echo "Linting and building project"
+    unit-tests:
+        runs-on: ubuntu-latest
+        # Prevents a workflow run from failing when a job fails. Set to true to allow a workflow run to pass when this job fails.
+        # continue-on-error: true
+        steps:
+            - name: Running unit tests
+              run: echo "Running tests..."
+            - name: Failing tests
+              if: ${{ !inputs.pass-unit-tests }}
+              run: exit 1
+    deploy-nonprod:
+        runs-on: ubuntu-latest
+        needs:
+            - lint-build
+            - unit-tests
+        steps:
+            - name: Deploying to nonprod
+              run: echo "Deploying to nonprod..."
+    e2e-tests:
+        runs-on: ubuntu-latest
+        needs: deploy-nonprod
+        steps:
+            - name: Running E2E tests
+              run: echo "Running E2E tests"
+    load-tests:
+        runs-on: ubuntu-latest
+        needs: deploy-nonprod
+        steps:
+            - name: Running load tests
+              run: echo "Running load tests"
+    deploy_prod:
+        runs-on: ubuntu-latest
+        needs:
+            - e2e-tests
+            - load-tests
+        steps:
+            - name: Deploying to prod
+              run: echo "Deploying to prod..."
